services:
  - type: web
    name: {{cookiecutter.project_slug}}
    env: python
    plan: free
    runtime: python-{{cookiecutter.python_version}}
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn {{cookiecutter.project_slug}}.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: {{cookiecutter.project_slug}}-db
          property: connectionString

databases:
  - name: {{cookiecutter.project_slug}}-db
    plan: free